default_platform(:ios)

platform :ios do
  desc "Build debug .app"
  lane :build_debug do
    build_ios_app(
      scheme: "WorkoutJournal",
      configuration: "Debug",
      skip_package_ipa: true,
      skip_archive: true,
      destination: "generic/platform=iOS Simulator",
      output_directory: "./build",
      output_name: "WorkoutJournal-debug"
    )
  end

  desc "Build release .ipa (unsigned)"
  lane :build_release do
    build_ios_app(
      scheme: "WorkoutJournal",
      configuration: "Release",
      export_method: "development",
      output_directory: "./build",
      output_name: "WorkoutJournal-release",
      skip_codesigning: true
    )
  end
end